language: php
dist: trusty
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm-3.22

matrix:
    allow_failures:
        - php: hhvm-3.22

before_script:
  - "cp app/config/parameters.yml{.dist,}"
  - "composer install --prefer-source"
  - "composer require --dev phpunit/phpunit --profile -vvv"

script: phpunit -c app
