language: php
dist: trusty
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - "cp app/config/parameters.yml{.dist,}"
  - "composer install --prefer-source"

script: phpunit -c app
