# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ AdminBundle ]
    assets:
        vizjs:
            inputs: "../node_modules/viz.js/viz.js"
    filters:
        cssrewrite: ~
        less:
            node_paths: [ %kernel.root_dir%/../node_modules ]

braincrafted_bootstrap:
    jquery_path: %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
    icon_prefix: fa
    customize:
      variables_file: %kernel.root_dir%/Resources/less/variables.less
      bootstrap_template: ThemingBundle:Bootstrap:bootstrap.less.twig

knp_menu:
    twig:
      template: "AppBundle:Menu:bootstrap.html.twig"
