imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: pdo_sqlite
        path: '%kernel.root_dir%/test_db.sqlite'

auth_request:
    enabled: true

email_rules:
    enabled: true
    rules:
      - { domain: example.com, groups: ['group_1', 'group_3'] }
      - { domain: example.invalid, role: ROLE_AUDIT, groups: ['group_1'] }
      - { regex_match: '/\.invalid$/', reject: true }
