home:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: user_profile

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

oauth_server:
    resource: "@OAuthBundle/Resources/config/routing/oauth.yml"
    type: rest
    prefix:   /new-oauth2

app_security:
    resource: "@AppBundle/Resources/config/routing/security.yml"

oauth_wellknown:
    prefix: /.well-known
    resource: "@OAuthBundle/Resources/config/routing/well_known.yml"

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix: admin
    type: rest

admin_dashboard_redirect:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin_dashboard

api:
    resource: "@UserBundle/Resources/config/routing/api.yml"
    prefix: /api
    type: rest

user:
    resource: "@UserBundle/Resources/config/routing/user.yml"
    prefix: /usr

user_public:
    resource: "@UserBundle/Resources/config/routing/public.yml"
    prefix: /pub

registration:
    resource: "@RegistrationBundle/Resources/config/routing.xml"
    prefix: /pub

auth_request:
    resource: "@AuthRequestBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest

plugin:
    resource: .
    type: plugin
